### ISSUE TITLE
[Question] About GPU requirements

### ISSUE THREAD

**Issue by zhengyuan-xie** [Shengcao-Cao/groundLMM#1]
### Question

Hi, thanks for your great work! I wonder about the minimal GPU requirements for running the experiments. Looking for your reply!

**Comment by Shengcao-Cao** [comment]
Hi @zhengyuan-xie ,

Thanks for your interest in our work!

Similar to LLaVA-1.5-7B, I think one GPU with 20GB memory should be adequate for running some inference. However, if you would like to reproduce the training procedure, 4-8 GPUs with 40+GB memory would be recommended.

Best,
Shengcao
